### ISSUE TITLE
Can't post attachments

### ISSUE THREAD

**Issue by austinhuang0131** [stevengum97/DiscordConnector#8]
```
2017-11-06T01:30:25.947068+00:00 app[web.1]: (node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: msgWithAttachments.forEach is not a function
```
* Just a normal text message with an image, no cards

**Comment by stevengum97** [comment]
@austinhuang0131 can you post the code you're using when you get this error?

**Comment by austinhuang0131** [comment]
An example would be https://github.com/austinhuang0131/metagon_plus/blob/master/index.js, line 464 to 494. The essential part is
```js
session.endDialog({
	attachments: [
		{
			contentType: "image/*",
			contentUrl: body.file // Valid URL
		}
	]
});
```

**Comment by stevengum97** [comment]
@austinhuang0131, thanks for reporting the issue. The root cause was a case where  `DiscordConnector.activityAttachmentsHandler()` would return a [single attachment](https://github.com/stevengum97/DiscordConnector/blob/ad53a37f443e432ea7d57906f6e9d690dde63b9f/DiscordConnector.js#L214), and not an array of a single attachment. I've already pushed a [fix](https://github.com/stevengum97/DiscordConnector/blob/7dbdae0b81ce36b79ca36e93b2b2d01fe3146ae3/DiscordConnector.js#L214) for this method and will try to do a new release tomorrow.

**Comment by austinhuang0131** [comment]
@stevengum97, The error is gone but the image still isn't sent.

**Comment by austinhuang0131** [comment]
@stevengum97 It looks like the error is fixed but the bot posts a small embed below the image :(

![screen shot 2017-11-07 at 3 56 41 pm](https://user-images.githubusercontent.com/16656689/32517394-522b4f20-c3d4-11e7-82da-603d364283a7.png)

**Comment by stevengum97** [comment]
Hmm I'll look into that... I just noticed that on my testbot as well.
